# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Validate
on:
    push:
        branches-ignore:
            - dependabot/**
    pull_request:
    workflow_dispatch:
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    DOTNET_NOLOGO: true
jobs:
    validate:
        runs-on: windows-2022
        steps:
            - name: Clone repository
              uses: actions/checkout@v3.5.3
              with:
                  submodules: recursive
            - name: Set up .NET
              uses: actions/setup-dotnet@v3.2.0
            - name: Validate sheets
              run: |
                  dotnet tool restore
                  dotnet novadrop-dc validate sheets
